import { FONTS } from "../../styles/GlobalStyles";

export const styles = (mode: boolean) => ({
    signinContainer: {
        width: '100%',
        px: 4,
        py: 2,
        position: 'absolute',
        top: 0,
        left: 0,
        zIndex: 10,
        fontFamily: FONTS.primary,
        backgroundColor: 'transparent',
    },
    logo: {
        color: mode ? '#fff' : '#0a0a0a',
        fontWeight: 400,
        textDecoration: 'none',
        fontFamily: FONTS.primary,
    },
    mainSection: {
        minHeight: '100vh',
        px: { xs: 3, sm: 6 },
        py: { xs: 10, sm: 12 },
        pt: 14,
        backgroundColor: mode ? '#0A0C21' : '#F9F9FF',
        color: mode ? '#fff' : '#111',
        backgroundImage: mode
          ? 'radial-gradient(#1a1d40 1px, transparent 1px)'
          : 'radial-gradient(#e5e5ff 1px, transparent 1px)',
        backgroundSize: '20px 20px, 100% 100%',
        display: 'flex',
        flexDirection: { xs: 'column', md: 'row' },
        alignItems: 'center',
        justifyContent: 'center',
        gap: { xs: 8, md: 12 },
        textAlign: { xs: 'center', md: 'left' },
    },
    leftContainer: { maxWidth: 500 },
    leftTypoOne: {
        fontWeight: 'bold',
        mb: 1,
        fontSize: { xs: '2.5rem', sm: '3rem' },
        letterSpacing: -1,
        fontFamily: FONTS.primary,
        color: mode ? '#fff' : '#0a0a0a',
    },
    leftTypoTwo: {
        color: mode ? '#b388ff' : '#7b4fff',
        mb: 4,
        fontWeight: 500,
        fontSize: { xs: '2rem', sm: '2.5rem' },
        fontFamily: FONTS.primary,
    },
    button: {
        color: mode ? '#fff' : '#0a0a0a',
        borderColor: mode ? '#fff' : '#0a0a0a',
        textTransform: 'none',
        borderRadius: '12px',
        fontSize: '1rem',
        fontFamily: FONTS.primary,
        py: 1.5,
        transition: 'all 0.3s ease',
        '&:hover': {
            borderColor: mode ? '#b388ff' : '#7b4fff',
            backgroundColor: mode ? 'rgba(255, 255, 255, 0.08)' : 'rgba(0, 0, 0, 0.04)',
        },
    },
    caption: {
        color: mode ? '#bbb' : '#666',
        mt: 1,
        textAlign: 'center',
        fontSize: '0.80rem',
        lineHeight: 1.5,
        fontFamily: FONTS.primary,
    },
    contexts: {
        fontSize: { xs: '1rem', sm: '1.2rem' },
        lineHeight: 1.8,
        fontFamily: FONTS.primary,
        color: mode ? '#fff' : '#0a0a0a',
    },
});