import { FONTS } from '../../styles/GlobalStyles';
import lightHeroBg from '../assets/lightBg.svg';

export const styles = (mode: boolean) => ({
    mainSection: {
        position: 'relative',
        width: '100%',
        minHeight: '100vh',
        height: 'auto',
        backgroundColor: mode ? '#0A0C21' : '#f5f5f5',
        backgroundImage: mode 
            ? `url('${lightHeroBg}')` 
            : `radial-gradient(circle at 1px 1px, rgba(0, 0, 0, 0.1) 1px, transparent 0)`,
        backgroundSize: mode ? 'cover' : '40px 40px',
        backgroundRepeat: mode ? 'no-repeat' : 'repeat',
        backgroundPosition: 'center',
        display: 'flex',
        flexDirection: 'column',
        overflow: 'hidden',
        pb: { xs: 4, md: 0 },
        transition: 'all 0.3s ease',
        ...(!mode && {
            '&::before': {
                content: '""',
                position: 'absolute',
                top: 0,
                left: 0,
                right: 0,
                bottom: 0,
                background: 'linear-gradient(135deg, rgba(245, 245, 245, 0.9) 0%, rgba(245, 245, 245, 0.7) 100%)',
                zIndex: -1,
            }
        })
    },

    tool: { 
        justifyContent: 'space-between',
        py: { xs: 1, md: 0 },
    },
    menuContainer: {
        display: { xs: 'flex', md: 'none' },
        ml: 'auto',
        alignItems: 'center',
    },
    mobileThemeToggle: {
        display: { xs: 'flex', md: 'none' },
        mr: 1,
    },
    themeToggle: {
        color: mode ? '#fff' : '#333',
        '&:hover': {
            backgroundColor: mode ? 'rgba(255, 255, 255, 0.1)' : 'rgba(0, 0, 0, 0.04)',
        },
    },
    menuButton: {
        p: { xs: '8px', sm: '12px' },
    },
    menuIcon: { 
        color: mode ? '#fff' : '#333',
        fontSize: { xs: '1.5rem', sm: '1.75rem' },
    },
    menu: {
        display: { xs: 'block', md: 'none' },
        '& .MuiPaper-root': {
            backgroundColor: mode ? '#0A0C21' : '#fff',
            color: mode ? '#fff' : '#333',
        },
    },
    menuTypo: {
        fontFamily: FONTS.primary,
        fontSize: { xs: '0.9rem', sm: '1rem' },
        color: mode ? '#fff' : '#333',
        textDecoration: 'none',
    },
    menuSignInItem: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: 1,
    },
    menuSignInIcon: {
        fontSize: '1rem',
        color: mode ? '#fff' : '#333',
    },
    logoImage: {
        height: { xs: 80, sm: 100, md: 120 },
        width: 'auto',
        display: 'block',
        cursor: 'pointer',
        mt: 1,
        filter: mode ? 'brightness(0) invert(1)' : 'none',
    },
    navItems: {
        display: { xs: 'none', md: 'flex' },
        gap: { md: 3, lg: 4 },
        position: 'absolute',
        left: '50%',
        transform: 'translateX(-50%)',
    },
    navItem: {
        position: 'relative',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        color: mode ? '#fff' : '#333',
        cursor: 'pointer',
        fontWeight: 500,
        fontFamily: FONTS.secodary,
        fontSize: { md: '0.9rem', lg: '1rem' },
        px: 1,
        py: 0.5,
        '&::after': {
            content: '""',
            position: 'absolute',
            left: 0,
            bottom: 0,
            height: '2px',
            width: '0%',
            backgroundColor: mode ? '#fff' : '#333',
            transition: 'width 0.3s ease-out',
        },
        '&:hover::after': {
            width: '100%',
        },
    },
    account: {
        px: { xs: 2, sm: 3, md: 4 },
        py: { xs: 0.8, sm: 1 },
        gap: 1,
        fontWeight: 500,
        fontSize: { xs: '0.85rem', sm: '0.95rem', md: '1rem' },
        fontFamily: FONTS.secodary,
        textTransform: 'none',
        borderRadius: '30px',
        borderColor: mode ? '#fff' : '#333',
        color: mode ? '#fff' : '#333',
        minWidth: 'unset',
        '&:hover': {
            backgroundColor: mode ? 'rgba(255, 255, 255, 0.1)' : 'rgba(0, 0, 0, 0.04)',
            borderColor: mode ? '#fff' : '#333',
        },
    },
    accountIcon: {
        fontSize: { xs: '1rem', sm: '1.1rem' },
        color: mode ? '#fff' : '#333',
    },
    heroContext: {
        flex: 1,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        textAlign: 'center',
        px: { xs: 2, sm: 3 },
        py: { xs: 4, md: 0 },
    },
    heroContent: {
        width: '100%',
        maxWidth: { xs: '100%', sm: '90%', md: '80%', lg: '100%' },
        mx: 'auto',
    },
    welcomeCon: {
        px: { xs: 1.5, sm: 2 },
        py: { xs: 0.8, sm: 1 },
        borderRadius: '50px',
        backdropFilter: 'blur(10px)',
        backgroundColor: mode ? 'rgba(255, 255, 255, 0.1)' : 'rgba(0, 0, 0, 0.1)',
        border: mode ? '1px solid rgba(255, 255, 255, 0.2)' : '1px solid rgba(0, 0, 0, 0.2)',
        boxShadow: '0 4px 20px rgba(0, 0, 0, 0.2)',
        display: 'inline-block',
        cursor: 'default',
        mb: { xs: 1.5, sm: 2 },
    },
    welcomeTypo: {
        fontWeight: 400,
        fontSize: { xs: '0.9rem', sm: '0.8rem' },
        color: mode ? '#ffffff' : '#333',
        fontFamily: FONTS.primary,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 0.5,
    },
    welcomeIcon: { 
        fontSize: { xs: '0.9rem', sm: '1rem', md: '1.1rem' },
        color: mode ? '#fff' : '#333',
    },
    mainTypo: {
        fontFamily: FONTS.primary,
        fontWeight: 500,
        fontSize: {
            xs: '2.6rem',
            sm: '2.5rem',
            md: '3.2rem',
            lg: '4rem',
            xl: '4.5rem',
        },
        color: mode ? '#fff' : '#333',
        my: 3,
        textAlign: "center",
    },
    subtitle: {
        mt: { xs: 0.5, sm: 1 },
        mb: 3,
        color: mode ? '#D3D3D3' : '#555',
        fontWeight: 300,
        fontFamily: FONTS.secodary,
        fontSize: {
            xs: '1rem',
            sm: '1.05rem',
            md: '1.15rem',
            lg: '1.25rem',
        },
    },
    bottomButtons: {
        display: 'flex',
        flexDirection: 'row',
        gap: { xs: 1.5, sm: 2 },
        justifyContent: 'center',
        alignItems: 'center',
        mt: { xs: 2, sm: 3 },
    },
    leftButton: {
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        gap: 0.5,
        px: { xs: 3, sm: 4 },
        py: { xs: 1, sm: 1.5 },
        fontSize: { xs: '0.85rem', sm: '0.95rem', md: '1rem' },
        fontFamily: FONTS.primary,
        textTransform: 'none',
        borderRadius: '30px',
        background: mode ? 'linear-gradient(135deg, #6e4cff, #a06fff)' : 'linear-gradient(135deg, #8a6eff, #b18aff)',
        boxShadow: mode ? '0 4px 20px rgba(160, 111, 255, 0.4)' : '0 4px 20px rgba(138, 110, 255, 0.4)',
        color: '#fff',
        '&:hover': {
            background: mode ? 'linear-gradient(135deg, #7e5eff, #b178ff)' : 'linear-gradient(135deg, #9a7eff, #c19aff)',
        },
        whiteSpace: 'nowrap',
    },
    rightButton: {
        px: { xs: 3, sm: 4 },
        py: { xs: 1, sm: 1.5 },
        fontSize: { xs: '0.85rem', sm: '0.95rem', md: '1rem' },
        fontFamily: FONTS.secodary,
        textTransform: 'none',
        borderRadius: '30px',
        borderColor: mode ? '#fff' : '#333',
        color: mode ? '#fff' : '#333',
        whiteSpace: 'nowrap',
        '&:hover': {
            backgroundColor: mode ? 'rgba(255, 255, 255, 0.1)' : 'rgba(0, 0, 0, 0.04)',
            borderColor: mode ? '#fff' : '#333',
        },
    },
    buttonIcon: {
        fontSize: { xs: '1rem', sm: '1.1rem' },
        color: '#fff',
    }
});