import { FONTS } from '../../styles/GlobalStyles';
import herobg from '../assets/herobg.svg';

export const styles = {
    mainSection: {
        position: 'relative',
        width: '100vw',
        height: '100vh',
        backgroundColor: '#0A0C21',
        backgroundImage: `url('${herobg}')`,
        backgroundSize: 'cover',
        backgroundRepeat: 'no-repeat',
        backgroundPosition: 'center',
        display: 'flex',
        flexDirection: 'column',
        overflow: 'hidden',
    },
    tool: { justifyContent: 'space-between' },
    menuContainer: {
        mr: 2,
        display: { xs: 'flex', md: 'none' },
    },
    menuIcon: { color: '#fff' },
    menu: {
        display: { xs: 'block', md: 'none' },
    },
    menuTypo: {
        fontFamily: FONTS.primary
    },
    logo: {
        color: '#fff',
        fontWeight: 400,
        fontFamily: FONTS.primary,
        textDecoration: 'none',
    },
    navItems: {
        display: { xs: 'none', md: 'flex' },
        gap: 4,
        position: 'absolute',
        left: '50%',
        transform: 'translateX(-50%)',
    },
    navItem: {
        position: 'relative',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        color: '#fff',
        cursor: 'pointer',
        fontFamily: FONTS.primary,
        px: 1,
        py: 0.5,
        '&::after': {
            content: '""',
            position: 'absolute',
            left: 0,
            bottom: 0,
            height: '2px',
            width: '0%',
            backgroundColor: '#fff',
            transition: 'width 0.3s ease-out',
        },
        '&:hover::after': {
            width: '100%',
        },
    },
    account: {
        px: 4,
        py: 0.5,
        gap: 1,
        fontSize: '1rem',
        fontFamily: FONTS.primary,
        textTransform: 'none',
        borderRadius: '30px',
        borderColor: '#fff',
        color: '#fff',
        '&:hover': {
            backgroundColor: 'rgba(255, 255, 255, 0.1)',
            borderColor: '#fff',
        },
    },
    heroContext: {
        flex: 1,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        textAlign: 'center',
        px: 2,
    },
    welcomeCon: {
        px: 2,
        py: 1,
        borderRadius: '50px',
        backdropFilter: 'blur(10px)',
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        border: '1px solid rgba(255, 255, 255, 0.2)',
        boxShadow: '0 4px 20px rgba(0, 0, 0, 0.2)',
        display: 'inline-block',
        cursor: 'default',
        mb: 2,
    },
    welcomeTypo: {
        fontWeight: 400,
        fontSize: '0.8rem',
        color: '#ffffff',
        fontFamily: FONTS.primary,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 0.5,
    },
    welcomeIcon: { fontSize: 18 },
    mainTypo: {
        fontFamily: FONTS.primary,
        fontWeight: 500,
        fontSize: {
            xs: '2.2rem',
            sm: '2.8rem',
            md: '3.8rem',
            lg: '4.5rem',
        },
        color: '#fff',
        mb: 2,
    },
    subtitle: {
        mt: 1,
        mb: 3,
        color: '#ffffffcc',
        fontWeight: 300,
        fontFamily: FONTS.primary,
        fontSize: {
            xs: '1rem',
            sm: '1.1rem',
            md: '1.25rem',
        }
    },
    bottomButtons: {
        display: 'flex',
        flexDirection: { xs: 'column', sm: 'row' },
        gap: 2,
        justifyContent: 'center',
        alignItems: 'center',
    },
    leftButton: {
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        gap: 1,
        px: 4,
        py: 1.5,
        fontSize: '1rem',
        fontFamily: FONTS.primary,
        textTransform: 'none',
        borderRadius: '30px',
        background: 'linear-gradient(135deg, #6e4cff, #a06fff)',
        boxShadow: '0 4px 20px rgba(160, 111, 255, 0.4)',
        '&:hover': {
            background: 'linear-gradient(135deg, #7e5eff, #b178ff)',
        },
    },
    rightButton: {
        px: 4,
        py: 1.5,
        fontSize: '1rem',
        fontFamily: FONTS.primary,
        textTransform: 'none',
        borderRadius: '30px',
        borderColor: '#fff',
        color: '#fff',
        '&:hover': {
            backgroundColor: 'rgba(255, 255, 255, 0.1)',
            borderColor: '#fff',
        },
    }
}