import { FONTS } from "../../styles/GlobalStyles";

export const getStyles = (mode: boolean) => ({
  headerContainer: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    mb: { xs: 6, md: 12 },
    px: { xs: 2, md: 2 },
  },
  logo: {
    color: mode ? '#fff' : '#0A0C21',
    fontWeight: 600,
    fontFamily: FONTS.primary,
  },
  nav: {
    display: { xs: 'none', md: 'flex' },
    alignItems: 'flex-start',
    gap: 4,
    position: 'relative',
    bgcolor: mode ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.06)',
    borderRadius: '50px',
    px: 1,
    py: 1,
    backdropFilter: 'blur(10px)',
  },
  logoBubble: {
    position: 'absolute',
    top: '-5px',
    right: '-20px',
    width: 64,
    height: 64,
    borderRadius: '50%',
    background: 'linear-gradient(90deg, #4E3C91, #939BF9)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 700,
    fontSize: '1.5rem',
    color: '#fff',
    boxShadow: '0 0 12px rgba(127, 90, 240, 0.5)',
  },
  mobileLogo: {
    width: 44,
    height: 44,
    borderRadius: '50%',
    background: 'linear-gradient(90deg, #4E3C91, #939BF9)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 700,
    fontSize: '1.25rem',
    color: '#fff',
  },
  drawerPaper: {
    background: mode ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.06)',
    backdropFilter: 'blur(10px)',
    color: mode ? '#fff' : '#0A0C21',
  },
  menuIcon: {
    color: mode ? '#fff' : '#0A0C21',
  },
  navItem: (isActive: boolean) => ({
    color: isActive ? '#fff' : (mode ? '#bbb' : '#666'),
    fontWeight: 300,
    borderRadius: '999px',
    background: isActive ? 'linear-gradient(90deg, #4E3C91, #939BF9)' : 'transparent',
    textTransform: 'none',
    px: 3,
    py: 1,
    fontSize: '0.95rem',
    fontFamily: FONTS.primary,
    transition: '0.3s',
    '&:hover': {
      background: 'linear-gradient(90deg, #4E3C91, #939BF9)',
      color: '#fff',
    },
  }),
  drawerItem: (isActive: boolean) => ({
    color: isActive ? '#fff' : (mode ? '#bbb' : '#666'),
    fontWeight: isActive ? 500 : 300,
  }),
});